title: 王鲸清的个人主页
page-top-title: 王鲸清
top-section-bg-text: 
home-subtitle: Jingqing Wang&ensp;|&ensp;王鲸清

awards-subtitle: "奖项荣誉"
experience-subtitle: "经历"
publications-subtitle: "发表论文"
nav-home: "首页"
nav-awards: "奖项"
nav-experience: "经历"
nav-publications: "论文"

copyright-text: '&copy; Jingqing Wang. 保留所有权利。'
