title: Jingqing Wang's Homepage
page-top-title: Jingqing Wang
top-section-bg-text: 
home-subtitle: Jingqing Wang&ensp;|&ensp;王鲸清

awards-subtitle: "Awards"
experience-subtitle: "Experience"
publications-subtitle: "Publications"
updates-subtitle: "Updates"
nav-home: "HOME"
nav-awards: "AWARDS"
nav-experience: "EXPERIENCE"
nav-publications: "PUBLICATIONS"
nav-updates: "UPDATES"

copyright-text: '&copy; Jingqing Wang. All Rights Reserved.'
